### PR TITLE
First pass at updated docs for wrapper scripts.

### PR DESCRIPTION
**Pull request by mareuter**

### CODE REVIEW

**Comment by mareuter** [comment]
The Docker container doesn't need the drun_static because that is how the environment is setup.

**Comment by rhiannonlynne** [comment]
I think you might mention this somewhere, but you could explicitly call it
out here when talking about the drun_static.

**Comment by mareuter** [comment]
Sure. I'll do that.

**Comment by rhiannonlynne** [comment]
Looks good to me! It's helpful to have the user actually warned about not using drun_static and why not (because of the container names it seems) -- that is helpful to have spelled out!

**Pull request merged**
