### PR TITLE
Bugfix/sim 2409 fix config save without savedir

### PR DESCRIPTION
**Pull request by mareuter**

### CODE REVIEW

**Comment by rhiannonlynne** [comment]
Looks fine to me. 
You could consider rewording the help strings with the flags to read something like .. 

--save-config    Flag to save the simulation configuration files.
                        If set, the configuration files will be saved to a directory set
                        by config-save-dir. 
                        Default is False, to not save the configuration files.
--config-save-dir CONFIG_SAVE_DIR
                        Set the directory to save the configuration files.
                        Default: "config_<sessionID>", in the execution directory.
                       The default behavior will be to save to a directory named
                       config_<sessionId> in the current (execution) directory, if save-config is set.


(I think this may more closely follow a user's logic -- do I save the config files? if so, where?)

**Comment by mareuter** [comment]
No, that isn't quite right. If a directory is passed by --config-save-dir (say _foo_) the resulting saved directory will be _foo/config_NNNN_. The directory passed does not replace _config_NNNN_. That is created no matter what as long as --save-config is used.

**Comment by rhiannonlynne** [comment]
Ah. I did not get that from the previous docstring either. Would it be more precise to say "config-save-path" essentially? (you have no control over the final directory, but you do have control over where that directory will be .. so the path, right?)

**Comment by mareuter** [comment]
Yes, that would probably be more precise. I can change the name if you'd like but we'll need to tell Kem that his notes on running need to updated.

**Comment by rhiannonlynne** [comment]
Your call. Even if you don't change the flag name, you could change the text in the docstring. I guess it would actually be something like 
--save-config:  If set, a directory called "config_<sessionId>" will be created at the location of save-config-dir.
--save-config-dir: Set the path to the configuration save directory. Default: execution directory.

**Comment by mareuter** [comment]
OK, I did change the name, did some more wordsmithing and added a section in the usage docs. Please have a look.

**Comment by rhiannonlynne** [comment]
Looks good to me. Thanks Michael!

**Pull request merged**
